name: Myliewood
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4604707339312881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00b8d0'
    - '#f7adce'
    - '#4572a1'
    - '#7fcfe2'
  brandStrength: 0.5328590059652925
  lightness: 0.3664877759292722
  saturation: 0.5746117455419153
  rhythmicContrast: 0.5749605181626976
purpose: []
